### PR TITLE
Automate building for Windows and macOS (amd64 and arm64) when new release is created

### PR DESCRIPTION
**Pull request by xiJulian**
The macOS build script now builds for two architectures (amd64 and arm64).
I've also added a GitHub Actions workflow that automatically builds and uploads Windows and macOS apps when a new release is created.

### CODE REVIEW

**Comment by kercre123** [comment]
The macOS build fails:

```
Done running the AppleScript...
Fixing permissions...
Done fixing permissions
Skipping blessing on sandbox
Deleting .fseventsd
Unmounting disk image...
hdiutil: couldn't eject "disk2" - Resource busy
Wait a moment...
Unmounting disk image...
hdiutil: couldn't eject "disk2" - Resource busy
Wait a moment...
Unmounting disk image...
hdiutil: couldn't eject "disk2" - Resource busy
Error: Process completed with exit code 16.
```

**Comment by xiJulian** [comment]
@kercre123 this shouldn't happen but create-dmg is weird sometimes. could you try re-running the job?

**Comment by kercre123** [comment]
Worked on the third try. I got this on the second try:

```
Creating dmg for arm64
Creating disk image...
Error: Process completed with exit code 1.
```

Maybe just needs some error handling for those two bits? Like, remove `set -e` from the script and make it so it repeats whenever the commands fail?

**Comment by xiJulian** [comment]
we can do that, or we can make the workflow automatically re-run if it fails

**Pull request merged**
